# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Thinking in Cities
email: eric@ericofftherails.city
description: >- # this means to ignore newlines until "baseurl:"
  Stories and thoughts of Community and Motion in our Urban Landscape. Here I will share my
  thoughts on cities, transportation, politics, and history.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ericofftherails.city" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dougli1sqrd
github_username: dougli1sqrd
logo: /assets/images/blog-logo-notext.png
avatarurl: /assets/images/house-rose-tree.png

feed_items: 10
feed_update_period: daily
feed_update_frequency: 1

# Build settings
theme: alembic-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-twitter-plugin
  - jekyll-paginate

paginate: 5
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: dougli1sqrd # jekyll-seo-tag > Owners twitter username
author: Eric # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Eric # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - "https://twitter.com/dougli1sqrd"



markdown: kramdown # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]


sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts


collections:
  posts:
    label: posts
    title: Posts # Needed for Siteleaf
    output: true
    # description: "My thoughts and ideas" # The post list page content
    feature_text: "Welcome to the blog"
    feature_image: "/assets/images/dolores-sunset.jpg"

  authors:
    output: true

navigation_header:
- title: Home
  url: /
- title: Posts
  url: /blog/
- title: About
  url: /about
- title: Contributors
  url: /contributors
- title: Categories
  url: /categories
- title: Contact
  url: /contact

navigation_footer:
- title: Created by Eric, Off the Rails
  url: www.twitter.com/dougli1sqrd

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: "https://twitter.com/dougli1sqrd"

sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#b13658"
  facebook: "#b13658"
  email: "#b13658"

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
